"""nfl live odds snapshot

Revision ID: 04b9ba998a20
Revises: 900520810b6b
Create Date: 2026-08-20 19:20:31.724978
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '04b9ba998a20'
down_revision: str | None = '900520810b6b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('nfl_games', sa.Column('live_total_line', sa.Float(), nullable=True))
    op.add_column('nfl_games', sa.Column('live_spread_line', sa.Float(), nullable=True))
    op.add_column('nfl_games', sa.Column('live_home_moneyline', sa.Integer(), nullable=True))
    op.add_column('nfl_games', sa.Column('live_away_moneyline', sa.Integer(), nullable=True))
    op.add_column('nfl_games', sa.Column('live_book_count', sa.Integer(), nullable=True))
    op.add_column('nfl_games', sa.Column('odds_fetched_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('nfl_games', 'odds_fetched_at')
    op.drop_column('nfl_games', 'live_book_count')
    op.drop_column('nfl_games', 'live_away_moneyline')
    op.drop_column('nfl_games', 'live_home_moneyline')
    op.drop_column('nfl_games', 'live_spread_line')
    op.drop_column('nfl_games', 'live_total_line')
    # ### end Alembic commands ###
