"""widen market and selection for per-event keys

Revision ID: 22485370401d
Revises: b9cc9afac67c
Create Date: 2026-08-20 16:37:10.716989
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '22485370401d'
down_revision: str | None = 'b9cc9afac67c'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('edges', 'market',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=48),
               existing_nullable=False)
    op.alter_column('edges', 'selection',
               existing_type=sa.VARCHAR(length=64),
               type_=sa.String(length=96),
               existing_nullable=False)
    op.alter_column('odds_snapshots', 'market',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=48),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('odds_snapshots', 'market',
               existing_type=sa.String(length=48),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.alter_column('edges', 'selection',
               existing_type=sa.String(length=96),
               type_=sa.VARCHAR(length=64),
               existing_nullable=False)
    op.alter_column('edges', 'market',
               existing_type=sa.String(length=48),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    # ### end Alembic commands ###
