"""initial schema

Revision ID: 3969973aa966
Revises: 
Create Date: 2026-08-19 17:38:25.028197
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '3969973aa966'
down_revision: str | None = None
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.String(length=32), nullable=False),
    sa.Column('endpoint', sa.String(length=128), nullable=False),
    sa.Column('sport_key', sa.String(length=32), nullable=True),
    sa.Column('requests_last', sa.Integer(), nullable=True),
    sa.Column('requests_used', sa.Integer(), nullable=True),
    sa.Column('requests_remaining', sa.Integer(), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('called_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_apiusage_called_at', 'api_usage', ['called_at'], unique=False)
    op.create_table('ingest_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job', sa.String(length=64), nullable=False),
    sa.Column('ok', sa.Boolean(), nullable=False),
    sa.Column('rows_written', sa.Integer(), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_ingestrun_job_started', 'ingest_runs', ['job', 'started_at'], unique=False)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Enum('MLB', 'NBA', name='sport', native_enum=False), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('espn_id', sa.Integer(), nullable=True),
    sa.Column('odds_api_name', sa.String(length=64), nullable=False),
    sa.Column('abbrev', sa.String(length=8), nullable=False),
    sa.Column('display_name', sa.String(length=64), nullable=False),
    sa.Column('location', sa.String(length=64), nullable=True),
    sa.Column('conference', sa.String(length=32), nullable=True),
    sa.Column('division', sa.String(length=32), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mlb_id'),
    sa.UniqueConstraint('sport', 'abbrev', name='uq_team_sport_abbrev')
    )
    op.create_index('ix_team_odds_name', 'teams', ['odds_api_name'], unique=False)
    op.create_table('players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Enum('MLB', 'NBA', name='sport', native_enum=False), nullable=False),
    sa.Column('mlb_id', sa.Integer(), nullable=True),
    sa.Column('full_name', sa.String(length=128), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.Column('primary_position', sa.String(length=16), nullable=True),
    sa.Column('throws', sa.String(length=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_players_mlb_id'), 'players', ['mlb_id'], unique=True)
    op.create_table('team_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Enum('MLB', 'NBA', name='sport', native_enum=False), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('source', sa.Enum('MLB_STATSAPI', 'ESPN', 'NBA_STATS', name='statsource', native_enum=False), nullable=False),
    sa.Column('games_played', sa.Integer(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('points_for', sa.Float(), nullable=True),
    sa.Column('points_against', sa.Float(), nullable=True),
    sa.Column('possessions', sa.Float(), nullable=True),
    sa.Column('pace', sa.Float(), nullable=True),
    sa.Column('off_rating', sa.Float(), nullable=True),
    sa.Column('def_rating', sa.Float(), nullable=True),
    sa.Column('runs_for', sa.Float(), nullable=True),
    sa.Column('runs_against', sa.Float(), nullable=True),
    sa.Column('team_era', sa.Float(), nullable=True),
    sa.Column('team_whip', sa.Float(), nullable=True),
    sa.Column('team_ops', sa.Float(), nullable=True),
    sa.Column('strikeout_rate', sa.Float(), nullable=True),
    sa.Column('walk_rate', sa.Float(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_id', 'season', 'source', name='uq_teamstats_team_season_source')
    )
    op.create_index('ix_teamstats_season_source', 'team_season_stats', ['season', 'source'], unique=False)
    op.create_table('games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Enum('MLB', 'NBA', name='sport', native_enum=False), nullable=False),
    sa.Column('external_id', sa.String(length=32), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('home_team_id', sa.Integer(), nullable=False),
    sa.Column('away_team_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('home_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('away_probable_pitcher_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['away_probable_pitcher_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['away_team_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['home_probable_pitcher_id'], ['players.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['home_team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sport', 'external_id', name='uq_game_sport_external')
    )
    op.create_index('ix_game_season', 'games', ['sport', 'season'], unique=False)
    op.create_index('ix_game_sport_start', 'games', ['sport', 'start_time'], unique=False)
    op.create_table('pitcher_game_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('hits', sa.Integer(), nullable=True),
    sa.Column('home_runs', sa.Integer(), nullable=True),
    sa.Column('decision', sa.String(length=4), nullable=True),
    sa.ForeignKeyConstraint(['opponent_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_date', 'opponent_id', name='uq_pitcherlog_unique')
    )
    op.create_index('ix_pitcherlog_player_date', 'pitcher_game_logs', ['player_id', 'game_date'], unique=False)
    op.create_table('pitcher_season_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('games_started', sa.Integer(), nullable=True),
    sa.Column('innings_pitched', sa.Float(), nullable=True),
    sa.Column('era', sa.Float(), nullable=True),
    sa.Column('whip', sa.Float(), nullable=True),
    sa.Column('k_per_9', sa.Float(), nullable=True),
    sa.Column('bb_per_9', sa.Float(), nullable=True),
    sa.Column('hr_per_9', sa.Float(), nullable=True),
    sa.Column('wins', sa.Integer(), nullable=True),
    sa.Column('losses', sa.Integer(), nullable=True),
    sa.Column('earned_runs', sa.Integer(), nullable=True),
    sa.Column('strikeouts', sa.Integer(), nullable=True),
    sa.Column('walks', sa.Integer(), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['player_id'], ['players.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'season', name='uq_pitcherstats_player_season')
    )
    op.create_table('edges',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('sport', sa.Enum('MLB', 'NBA', name='sport', native_enum=False), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('selection', sa.String(length=64), nullable=False),
    sa.Column('point', sa.Float(), nullable=True),
    sa.Column('best_book', sa.String(length=48), nullable=False),
    sa.Column('best_price_american', sa.Integer(), nullable=False),
    sa.Column('best_price_decimal', sa.Float(), nullable=False),
    sa.Column('fair_prob', sa.Float(), nullable=False),
    sa.Column('book_count', sa.Integer(), nullable=False),
    sa.Column('ev', sa.Float(), nullable=False),
    sa.Column('kelly_full', sa.Float(), nullable=False),
    sa.Column('kelly_quarter', sa.Float(), nullable=False),
    sa.Column('model_prob', sa.Float(), nullable=True),
    sa.Column('model_ev', sa.Float(), nullable=True),
    sa.Column('model_line', sa.Float(), nullable=True),
    sa.Column('signals_agree', sa.Boolean(), nullable=True),
    sa.Column('computed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_edge_game', 'edges', ['game_id'], unique=False)
    op.create_index('ix_edge_sport_ev', 'edges', ['sport', 'ev'], unique=False)
    op.create_table('game_team_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('opponent_id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_date', sa.Date(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points_for', sa.Integer(), nullable=False),
    sa.Column('points_against', sa.Integer(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=False),
    sa.Column('possessions', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['opponent_id'], ['teams.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['teams.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team_id', name='uq_gamelog_game_team')
    )
    op.create_index(op.f('ix_game_team_logs_season'), 'game_team_logs', ['season'], unique=False)
    op.create_index(op.f('ix_game_team_logs_team_id'), 'game_team_logs', ['team_id'], unique=False)
    op.create_table('odds_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('bookmaker', sa.String(length=48), nullable=False),
    sa.Column('market', sa.String(length=16), nullable=False),
    sa.Column('outcome', sa.String(length=64), nullable=False),
    sa.Column('price_american', sa.Integer(), nullable=False),
    sa.Column('point', sa.Float(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_odds_fetched', 'odds_snapshots', ['fetched_at'], unique=False)
    op.create_index('ix_odds_game_market_fetched', 'odds_snapshots', ['game_id', 'market', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_odds_game_market_fetched', table_name='odds_snapshots')
    op.drop_index('ix_odds_fetched', table_name='odds_snapshots')
    op.drop_table('odds_snapshots')
    op.drop_index(op.f('ix_game_team_logs_team_id'), table_name='game_team_logs')
    op.drop_index(op.f('ix_game_team_logs_season'), table_name='game_team_logs')
    op.drop_table('game_team_logs')
    op.drop_index('ix_edge_sport_ev', table_name='edges')
    op.drop_index('ix_edge_game', table_name='edges')
    op.drop_table('edges')
    op.drop_table('pitcher_season_stats')
    op.drop_index('ix_pitcherlog_player_date', table_name='pitcher_game_logs')
    op.drop_table('pitcher_game_logs')
    op.drop_index('ix_game_sport_start', table_name='games')
    op.drop_index('ix_game_season', table_name='games')
    op.drop_table('games')
    op.drop_index('ix_teamstats_season_source', table_name='team_season_stats')
    op.drop_table('team_season_stats')
    op.drop_index(op.f('ix_players_mlb_id'), table_name='players')
    op.drop_table('players')
    op.drop_index('ix_team_odds_name', table_name='teams')
    op.drop_table('teams')
    op.drop_index('ix_ingestrun_job_started', table_name='ingest_runs')
    op.drop_table('ingest_runs')
    op.drop_index('ix_apiusage_called_at', table_name='api_usage')
    op.drop_table('api_usage')
    # ### end Alembic commands ###
