"""nfl player games

Revision ID: 7d08e3e45fe4
Revises: 914dfb421b93
Create Date: 2026-08-20 20:05:20.343908
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '7d08e3e45fe4'
down_revision: str | None = '914dfb421b93'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_player_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('player_id', sa.String(length=24), nullable=False),
    sa.Column('player_name', sa.String(length=96), nullable=False),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('opponent', sa.String(length=4), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=True),
    sa.Column('passing_yards', sa.Float(), nullable=True),
    sa.Column('rushing_yards', sa.Float(), nullable=True),
    sa.Column('receiving_yards', sa.Float(), nullable=True),
    sa.Column('attempts', sa.Integer(), nullable=True),
    sa.Column('completions', sa.Integer(), nullable=True),
    sa.Column('carries', sa.Integer(), nullable=True),
    sa.Column('targets', sa.Integer(), nullable=True),
    sa.Column('receptions', sa.Integer(), nullable=True),
    sa.Column('target_share', sa.Float(), nullable=True),
    sa.Column('air_yards_share', sa.Float(), nullable=True),
    sa.Column('offense_snaps', sa.Integer(), nullable=True),
    sa.Column('snap_pct', sa.Float(), nullable=True),
    sa.Column('roof', sa.String(length=12), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('total_line', sa.Float(), nullable=True),
    sa.Column('team_spread', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('player_id', 'game_id', name='uq_nflplayergame_player_game')
    )
    op.create_index('ix_nflplayergame_opponent', 'nfl_player_games', ['opponent', 'season'], unique=False)
    op.create_index('ix_nflplayergame_player_season', 'nfl_player_games', ['player_id', 'season', 'week'], unique=False)
    op.create_index('ix_nflplayergame_pos_season', 'nfl_player_games', ['position', 'season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nflplayergame_pos_season', table_name='nfl_player_games')
    op.drop_index('ix_nflplayergame_player_season', table_name='nfl_player_games')
    op.drop_index('ix_nflplayergame_opponent', table_name='nfl_player_games')
    op.drop_table('nfl_player_games')
    # ### end Alembic commands ###
