"""widen nfl injury text columns

Revision ID: 900520810b6b
Revises: e1f168a5cf3b
Create Date: 2026-08-20 17:18:15.350175
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '900520810b6b'
down_revision: str | None = 'e1f168a5cf3b'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nfl_injuries', 'player_name',
               existing_type=sa.VARCHAR(length=96),
               type_=sa.String(length=128),
               existing_nullable=True)
    op.alter_column('nfl_injuries', 'report_status',
               existing_type=sa.VARCHAR(length=24),
               type_=sa.String(length=64),
               existing_nullable=True)
    op.alter_column('nfl_injuries', 'practice_status',
               existing_type=sa.VARCHAR(length=48),
               type_=sa.String(length=256),
               existing_nullable=True)
    op.alter_column('nfl_injuries', 'injury',
               existing_type=sa.VARCHAR(length=96),
               type_=sa.String(length=256),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('nfl_injuries', 'injury',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=96),
               existing_nullable=True)
    op.alter_column('nfl_injuries', 'practice_status',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=48),
               existing_nullable=True)
    op.alter_column('nfl_injuries', 'report_status',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=24),
               existing_nullable=True)
    op.alter_column('nfl_injuries', 'player_name',
               existing_type=sa.String(length=128),
               type_=sa.VARCHAR(length=96),
               existing_nullable=True)
    # ### end Alembic commands ###
