"""nfl line history

Revision ID: 914dfb421b93
Revises: 04b9ba998a20
Create Date: 2026-08-20 19:51:22.298689
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '914dfb421b93'
down_revision: str | None = '04b9ba998a20'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_line_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('hours_to_kickoff', sa.Float(), nullable=True),
    sa.Column('total_line', sa.Float(), nullable=True),
    sa.Column('spread_line', sa.Float(), nullable=True),
    sa.Column('home_moneyline', sa.Integer(), nullable=True),
    sa.Column('away_moneyline', sa.Integer(), nullable=True),
    sa.Column('book_count', sa.Integer(), nullable=True),
    sa.Column('model_total', sa.Float(), nullable=True),
    sa.Column('model_margin', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=16), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'fetched_at', name='uq_nfllinehist_game_time')
    )
    op.create_index('ix_nfllinehist_game', 'nfl_line_history', ['game_id', 'fetched_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nfllinehist_game', table_name='nfl_line_history')
    op.drop_table('nfl_line_history')
    # ### end Alembic commands ###
