"""nfl prop lines

Revision ID: ad5e92309e9a
Revises: 7d08e3e45fe4
Create Date: 2026-08-20 20:25:58.904236
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'ad5e92309e9a'
down_revision: str | None = '7d08e3e45fe4'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_prop_lines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('market', sa.String(length=32), nullable=False),
    sa.Column('player_name', sa.String(length=96), nullable=False),
    sa.Column('player_id', sa.String(length=24), nullable=True),
    sa.Column('bookmaker', sa.String(length=48), nullable=False),
    sa.Column('outcome', sa.String(length=16), nullable=False),
    sa.Column('point', sa.Float(), nullable=False),
    sa.Column('price_american', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'market', 'player_name', 'bookmaker', 'outcome', 'fetched_at', name='uq_nflpropline_obs')
    )
    op.create_index(op.f('ix_nfl_prop_lines_player_id'), 'nfl_prop_lines', ['player_id'], unique=False)
    op.create_index('ix_nflpropline_game_market', 'nfl_prop_lines', ['game_id', 'market'], unique=False)
    op.create_index('ix_nflpropline_player', 'nfl_prop_lines', ['player_name', 'season', 'week'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nflpropline_player', table_name='nfl_prop_lines')
    op.drop_index('ix_nflpropline_game_market', table_name='nfl_prop_lines')
    op.drop_index(op.f('ix_nfl_prop_lines_player_id'), table_name='nfl_prop_lines')
    op.drop_table('nfl_prop_lines')
    # ### end Alembic commands ###
