"""per-event markets: event ids, innings, prop players

Revision ID: b9cc9afac67c
Revises: 3969973aa966
Create Date: 2026-08-20 16:33:52.789302
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'b9cc9afac67c'
down_revision: str | None = '3969973aa966'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game_innings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=False),
    sa.Column('inning', sa.Integer(), nullable=False),
    sa.Column('home_runs', sa.Integer(), nullable=False),
    sa.Column('away_runs', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['game_id'], ['games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'inning', name='uq_inning_game_number')
    )
    op.add_column('games', sa.Column('odds_event_id', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_games_odds_event_id'), 'games', ['odds_event_id'], unique=False)
    op.add_column('odds_snapshots', sa.Column('player_name', sa.String(length=96), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('odds_snapshots', 'player_name')
    op.drop_index(op.f('ix_games_odds_event_id'), table_name='games')
    op.drop_column('games', 'odds_event_id')
    op.drop_table('game_innings')
    # ### end Alembic commands ###
