"""nfl tables

Revision ID: e1f168a5cf3b
Revises: 22485370401d
Create Date: 2026-08-20 17:14:04.611333
"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = 'e1f168a5cf3b'
down_revision: str | None = '22485370401d'
branch_labels: Sequence[str] | None = None
depends_on: Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('nfl_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('game_type', sa.String(length=8), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('gameday', sa.Date(), nullable=False),
    sa.Column('weekday', sa.String(length=12), nullable=True),
    sa.Column('gametime', sa.String(length=8), nullable=True),
    sa.Column('home_team', sa.String(length=4), nullable=False),
    sa.Column('away_team', sa.String(length=4), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('result', sa.Integer(), nullable=True),
    sa.Column('overtime', sa.Boolean(), nullable=False),
    sa.Column('spread_line', sa.Float(), nullable=True),
    sa.Column('total_line', sa.Float(), nullable=True),
    sa.Column('home_moneyline', sa.Integer(), nullable=True),
    sa.Column('away_moneyline', sa.Integer(), nullable=True),
    sa.Column('over_odds', sa.Integer(), nullable=True),
    sa.Column('under_odds', sa.Integer(), nullable=True),
    sa.Column('roof', sa.String(length=12), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('home_rest', sa.Integer(), nullable=True),
    sa.Column('away_rest', sa.Integer(), nullable=True),
    sa.Column('div_game', sa.Boolean(), nullable=False),
    sa.Column('stadium', sa.String(length=64), nullable=True),
    sa.Column('referee', sa.String(length=64), nullable=True),
    sa.Column('home_qb_name', sa.String(length=64), nullable=True),
    sa.Column('away_qb_name', sa.String(length=64), nullable=True),
    sa.Column('home_first_half', sa.Integer(), nullable=True),
    sa.Column('away_first_half', sa.Integer(), nullable=True),
    sa.Column('home_first_quarter', sa.Integer(), nullable=True),
    sa.Column('away_first_quarter', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id')
    )
    op.create_index(op.f('ix_nfl_games_away_team'), 'nfl_games', ['away_team'], unique=False)
    op.create_index(op.f('ix_nfl_games_home_team'), 'nfl_games', ['home_team'], unique=False)
    op.create_index(op.f('ix_nfl_games_roof'), 'nfl_games', ['roof'], unique=False)
    op.create_index('ix_nflgame_gameday', 'nfl_games', ['gameday'], unique=False)
    op.create_index('ix_nflgame_season_week', 'nfl_games', ['season', 'week'], unique=False)
    op.create_table('nfl_injuries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('player_name', sa.String(length=96), nullable=True),
    sa.Column('gsis_id', sa.String(length=24), nullable=True),
    sa.Column('position', sa.String(length=8), nullable=True),
    sa.Column('report_status', sa.String(length=24), nullable=True),
    sa.Column('practice_status', sa.String(length=48), nullable=True),
    sa.Column('injury', sa.String(length=96), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfl_injuries_gsis_id'), 'nfl_injuries', ['gsis_id'], unique=False)
    op.create_index('ix_nflinjury_season_week_team', 'nfl_injuries', ['season', 'week', 'team'], unique=False)
    op.create_table('nfl_team_games',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_pk', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.String(length=24), nullable=False),
    sa.Column('season', sa.Integer(), nullable=False),
    sa.Column('week', sa.Integer(), nullable=False),
    sa.Column('gameday', sa.Date(), nullable=False),
    sa.Column('team', sa.String(length=4), nullable=False),
    sa.Column('opponent', sa.String(length=4), nullable=False),
    sa.Column('is_home', sa.Boolean(), nullable=False),
    sa.Column('points_for', sa.Integer(), nullable=True),
    sa.Column('points_against', sa.Integer(), nullable=True),
    sa.Column('first_half_points', sa.Integer(), nullable=True),
    sa.Column('first_quarter_points', sa.Integer(), nullable=True),
    sa.Column('team_spread', sa.Float(), nullable=True),
    sa.Column('covered', sa.Boolean(), nullable=True),
    sa.Column('push_spread', sa.Boolean(), nullable=False),
    sa.Column('won', sa.Boolean(), nullable=True),
    sa.Column('total_line', sa.Float(), nullable=True),
    sa.Column('went_over', sa.Boolean(), nullable=True),
    sa.Column('push_total', sa.Boolean(), nullable=False),
    sa.Column('is_favourite', sa.Boolean(), nullable=True),
    sa.Column('rest', sa.Integer(), nullable=True),
    sa.Column('rest_advantage', sa.Integer(), nullable=True),
    sa.Column('roof', sa.String(length=12), nullable=True),
    sa.Column('surface', sa.String(length=16), nullable=True),
    sa.Column('temp', sa.Float(), nullable=True),
    sa.Column('wind', sa.Float(), nullable=True),
    sa.Column('div_game', sa.Boolean(), nullable=False),
    sa.Column('qb_name', sa.String(length=64), nullable=True),
    sa.Column('referee', sa.String(length=64), nullable=True),
    sa.Column('off_epa_per_play', sa.Float(), nullable=True),
    sa.Column('def_epa_per_play', sa.Float(), nullable=True),
    sa.Column('off_success_rate', sa.Float(), nullable=True),
    sa.Column('plays', sa.Integer(), nullable=True),
    sa.Column('pass_rate', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['game_pk'], ['nfl_games.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('game_id', 'team', name='uq_nflteamgame_game_team')
    )
    op.create_index(op.f('ix_nfl_team_games_opponent'), 'nfl_team_games', ['opponent'], unique=False)
    op.create_index('ix_nflteamgame_season_week', 'nfl_team_games', ['season', 'week'], unique=False)
    op.create_index('ix_nflteamgame_team_season', 'nfl_team_games', ['team', 'season'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_nflteamgame_team_season', table_name='nfl_team_games')
    op.drop_index('ix_nflteamgame_season_week', table_name='nfl_team_games')
    op.drop_index(op.f('ix_nfl_team_games_opponent'), table_name='nfl_team_games')
    op.drop_table('nfl_team_games')
    op.drop_index('ix_nflinjury_season_week_team', table_name='nfl_injuries')
    op.drop_index(op.f('ix_nfl_injuries_gsis_id'), table_name='nfl_injuries')
    op.drop_table('nfl_injuries')
    op.drop_index('ix_nflgame_season_week', table_name='nfl_games')
    op.drop_index('ix_nflgame_gameday', table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_roof'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_home_team'), table_name='nfl_games')
    op.drop_index(op.f('ix_nfl_games_away_team'), table_name='nfl_games')
    op.drop_table('nfl_games')
    # ### end Alembic commands ###
